#+TITLE: Max Masterton's unstable Doom Emacs Config
#+DESCRIPTION: Max Masterton's experimental configiration file for Doom Emacs, an emacs framework for the stubborn martian vimmer. -- Note: This is an experimental config --
#+PROPERTY: header-args :tangle ~/.doom.d/config.el
#+AUTHOR: Max Masterton

* Notes
This is an experimental config, so nothing is stable.
 + Control-C Control-C to refresh
 + M-x org-babel-tangle to tangle to config.el

 #+BEGIN_SRC elisp
;   ___ _ __ ___   __ _  ___ ___
;  / _ \ '_ ` _ \ / _` |/ __/ __|
; |  __/ | | | | | (_| | (__\__ \
;  \___|_| |_| |_|\__,_|\___|___/
;
 #+END_SRC

* The Preambles
The code in this section codes for default behaviours from doom emacs

** Name and Email
#+BEGIN_SRC elisp
(setq user-full-name "Max Masterton"
      user-mail-address "me@maxmasterton.tech"
      ;user-login-name "MaxTheMasterton"
      )
#+END_SRC

** Rudimentary Settings
#+BEGIN_SRC elisp
(setq-default
 delete-by-moving-to-trash t ; Delete files to trash
 tab-width 4 ; set tab width
 uniquify-buffer-name-style 'forward ; Uniquify buffer names
 window-combination-resize t ; Take window sapce from all existing windows
 x-stretch-cursor t ; Stretch cursor over long glyphs
 )

(setq undo-limit 80000000 ; Set undo limit to 80mb
      evil-want-fine-undo t ; More granular changes in insert mode
      auto-save-default t ; Auto save by default
      inhibit-compacting-font-caches t ; Load glyphs into memory
      truncate-string-ellipsis "..." ; Use unicode ellispis instead of "..."
      )

(delete-selection-mode 1) ; Replace selection when inerting text
(global-subword-mode 1) ; Iterate through CamelCase Words with evil bindings
#+END_SRC

** Evil Key Bindings
#+BEGIN_SRC elisp
(define-key evil-normal-state-map (kbd "SPC o i") 'eww)
(define-key evil-normal-state-map (kbd "SPC o l") 'elfeed)
#+END_SRC

** EWW
Links opened within emacs will open in eww rather than an external browser.

#+BEGIN_SRC elisp
(setq browse-url-browser-function 'eww-browse-url)
#+END_SRC

* Aesthetic Settings
There settings code for asethetic changes

** Fonts
Doom Exposes five (optional) variables for controlling fonts within doom. Here are the 3 important ones:
+ 'doom-font'
+ 'doom-variable-pitch-font'
+ 'doom-big-font' used for presentations and streaming

They all accept a font-spec, font-string ("Input Mono-12") or xldf font string, you generally only need these two:

#+BEGIN_SRC elisp
(setq doom-font (font-spec :family "JetBrains Mono" :size 13)
      doom-big-font (font-spec :family "JetBrains Mono" :size 30)
      ;doom-variable-pitch-font
      ;doom-serif-font
      )
#+END_SRC

*** Proportional Fonts
This codes for a function that can be called through M-x. It sets the font to a variable width proportional to fonts in the current buffer.

#+BEGIN_SRC elisp
(defun my-buffer-face-mode-variable ()
  "Set font to a variable width (proportional) fonts in the current buffer"
  (interactive)
  (setq buffer-face-mode-face '(family: "JetBrains Mono" :height 100))
  (buffer-face-mode))
(add-hook 'org-mode-hook 'my-buffer-face-mode-variable)
#+END_SRC

** Doom Dashboard
This configures the menu in the doom dashboard.

#+BEGIN_SRC elisp
(setq +doom-dashboard-menu-sections
    '(("Reload last session"
      :icon (all-the-icons-octicon "history" :face 'doom-dashboard-menu-title)
      :when (cond ((require 'persp-mode nil t)
                    (file-exists-p (expand-file-name persp-auto-save-fname persp-save-dir)))
                  ((require 'desktop nil t)
                    (file-exists-p (desktop-full-file-name))))
      :face (:inherit (doom-dashboard-menu-title bold))
      :action doom/quickload-session)
      ("Open File Manager"
       :icon (all-the-icons-octicon "file-directory" :face 'doom-dashboard-menu-title)
       :action dired-jump)
      ("Read Emails"
       :icon (all-the-icons-octicon "mail" :face 'doom-dashboard-menu-title)
       :action =mu4e)
      ("Open org-agenda"
      :icon (all-the-icons-octicon "calendar" :face 'doom-dashboard-menu-title)
      :when (fboundp 'org-agenda)
      :action org-agenda)
      ("Read the News"
       :icon (all-the-icons-octicon "globe" :face 'doom-dashboard-menu-title)
       :action elfeed)
      ("Recently opened files"
      :icon (all-the-icons-octicon "file-text" :face 'doom-dashboard-menu-title)
      :action recentf-open-files)
      ("Jump to a Bookmark"
      :icon (all-the-icons-octicon "file-symlink-file" :face 'doom-dashboard-menu-title)
      :action bookmark-jump)
      ("Edit Config"
      :icon (all-the-icons-octicon "gear" :face 'doom-dashboard-menu-title)
      :action doom/open-private-config)
      ("Open Terminal"
      :icon (all-the-icons-octicon "terminal" :face 'doom-dashboard-menu-title)
      :action +vterm/here)
      ("Browse the Web"
       :icon (all-the-icons-octicon "rss" :face 'doom-dashboard-menu-title)
       :action eww)
      ("Quit Emacs"
       :icon (all-the-icons-octicon "circle-slash" :face 'doom-dashboard-menu-title)
       :action evil-quit)
      ))
#+END_SRC

** Theme
There are two ways to load a theme. Both assume that the theme is installed and avaliable. You can either set 'doom-theme' or manually load a theme with the 'load-theme' option. I like moonlight because the colours stand out and the colours are consistent.

#+BEGIN_SRC elisp
(setq doom-theme 'doom-dracula)

;; Flagship themes
;(setq doom-theme 'doom-one
;      doom-theme 'doom-vibrant)

(delq! t custom-theme-load-path)
#+END_SRC

** Fancy Splash Image
An PNG or SVG Image can be inputed which will replace the DOOM ascaii art on the splashscreen / landing page.

#+BEGIN_SRC elisp
(setq fancy-splash-image "~/Images/Emacs-logo.svg")
#+END_SRC

#+RESULTS:
: my-startup-function

** Modeline Theme
The text to show files on the the modeline is red by default, to me this screams 'error' so I changed it to orange.

#+BEGIN_SRC elisp
(custom-set-faces!
  '(doom-modeline-buffer-modified :foreground "orange"))
#+END_SRC

** Transparency
The first argument codes for transparency when the given frame of emacs, the second for when the given frame is idle.

#+BEGIN_SRC elisp
(set-frame-parameter (selected-frame) 'alpha '(95 . 90))
(add-to-list 'default-frame-alist '(alpha . (95 . 90)))
#+END_SRC

* Modeline
** Doom Modeline
The Doom Modeline can also be customized by running 'M-x customize-group RET doom-modeline RET'

#+BEGIN_SRC elisp
(setq doom-modeline-height 25
      doom-modeline-bar-width 3
      )

(setq doom-modeline-icon (display-graphic-p)
      doom-modeline-buffer-notification-icon t
      ;doom-modeline-enable-word-count t ; Enables word count for a selected area
      doom-modeline-indent-info t
      doom-modeline-workspace-name t
      )

(setq doom-modeline-continuous-word-count-modes '(markdown-mode gfm-mode org-mode))
#+END_SRC

** Standard Modeline
Items visable on the standard GNU/emacs modeline are also visable on the doom-modeline.

#+BEGIN_SRC elisp
(display-time-mode 1)
(global-display-line-numbers-mode)
#+END_SRC

** Modeline Buffer Encoding
Almost everything that I edit is encoded in UTF-8 so it's only worth showing buffer encoding on the modeline if it's encoding in something other than UTF-8.

#+BEGIN_SRC elisp
(defun doom-modeline-conditional-buffer-encoding ()
  (setq-local doom-modeline-buffer-encoding
              (unless (or (eq buffer-file-coding-system 'utf-8-unix)
                          (eq buffer-file-coding-system 'utf-8)))))
(add-hook 'after-change-major-mode-hook #'doom-modeline-conditional-buffer-encoding
          )
#+END_SRC

* Other
** Org Mode Settings
If you use 'org' and you don't want your org files in the default location below, change the 'org-directory'. It must be set before org loads! Mine lives in a dedicated org directory.

#+BEGIN_SRC elisp
(after! org
  (setq org-directory "~/org/"
        ;org-agenda-files "~/org/agenda.org"
        org-log-done 'note
        )
  (require 'org-bullets)
  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
)
#+END_SRC

** Smooth Scrolling
While Sublimity offers a set of different features, some people are using just the smooth-scrolling:

#+BEGIN_SRC elisp
(require 'sublimity)
(require 'sublimity-scroll)
;(require 'sublimity-map) ; Doesn't interact well with minimap
(sublimity-mode 1)

(setq sublimity-scroll-weight1 0.8
      sublimity-scroll-weight2 0.8
      )
#+END_SRC

While Sublimity is nice, It's still neccessary to complete the following settings:

#+BEGIN_SRC elisp
(setq mouse-wheel-scroll-amount '(1 ((shift) . 1))
      mouse-wheel-progressive-speed t
      )
#+END_SRC

** Window Behaviour
The following code allows me to chose which buffer I want to see when I split a window. It first does a split to the right, and then opens ivy and shows me a preview.

#+BEGIN_SRC elisp
(setq evil-vsplit-window-right t
      evil-split-window-below t)
(defadvice! prompt-for-buffer (&rest _)
  :after '(evil-window-split evil-window-vsplit)
  (+ivy/switch-buffer))
(setq +ivy-buffer-preview t)
#+END_SRC

** Mu4e Email
Mu for emacs, my configiration

#+BEGIN_SRC elisp
(add-to-list 'load-path "/usr/local/share/emacs/site-lisp/mu4e")
(require 'mu4e)
(require 'smtpmail)
(setq mu4e-get-mail-command "mbsyncrc -c"
      mu4e-update-interval 300
      message-send-mail-function 'smtpmail-send-it
      starttls-use-gnutls t
      smtpmail-starttls-credentials '(("outlook.office365.com" 587 nil nil))
      smtpmail-auth-credentials '(("outlook.office365.com" 587 "m.masterton19@st-eds.co.uk" nil))
      smtpmail-default-smtp-server "outlook.office365.com"
      smtpmail-smtp-server "outlook.office365.com"
      smtpmail-smtp-service 587
      mu4e-sent-folder "/Sent"
      mu4e-drafts-folder "/Drafts"
      mu4e-trash-folder "/Trash"
      mu4e-refile-folder "/All Mail"
      mu4e-maildir-shortcuts
      '(("/max-school/Inbox"       . ?i)
        ("/max-school/Sent"        . ?s)
        ("/max-school/All Mail"    . ?a)
        ("/max-school/Trash"       . ?t))
      )
#+END_SRC

* Elfeed
An RSS Newfead reader for emacs
#+BEGIN_SRC elisp
(require 'elfeed-goodies)
(elfeed-goodies/setup)
(setq elfeed-goodies/entry-pane-size 0.5)
(evil-define-key 'normal elfeed-show-mode-map
  (kbd "J") 'elfeed-goodies/split-show-next
  (kbd "K") 'elfeed-goodies/split-show-prev)
(evil-define-key 'normal elfeed-search-mode-map
  (kbd "J") 'elfeed-goodies/split-show-next
  (kbd "K") 'elfeed-goodies/split-show-prev)

(setq elfeed-feeds (quote
                    (("https://www.reddit.com/r/linux.rss" reddit linux)
                     ("https://www.reddit.com/r/emacs.rss" reddit emacs)
                     ("https://distrowatch.com/news/dwd.xml" distrowatcg linux)
                     ("https://betanews.com/feed" betanews linux)
                     ("https://www.zdnet.com/topic/linux/rss.xml" zdnet linux)
                     ("https://cms.qz.com/re/rss" quartz news))))
#+END_SRC
